### ISSUE TITLE
toga-demo fails on debian 8 with python 3.4

### ISSUE THREAD

**Issue by mrm2m** [pybee/toga-demo#14]
```
Creating symlink (/home/moritz/projects/toga_venv/lib/python3.4/site-packages/gi & /home/moritz/projects/toga_venv/lib/python3.4/site-packages/pygtkcompat) to system GTK+ libraries...

(toga-demo:13991): GLib-GIO-CRITICAL **: g_application_set_application_id: assertion 'application_id == NULL || g_application_id_is_valid (application_id)' failed
Traceback (most recent call last):
  File "/home/moritz/projects/toga_venv/lib/python3.4/site-packages/toga_gtk/widgets/icon.py", line 20, in __impl
    return self._impl_cache[size]
KeyError: 32

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/moritz/projects/toga_venv/lib/python3.4/site-packages/toga_gtk/app.py", line 139, in _startup
    self.startup()
  File "/home/moritz/projects/toga_venv/lib/python3.4/site-packages/toga_demo/app.py", line 55, in startup
    self.main_window.toolbar = [cmd1, toga.SEPARATOR, cmd2]
  File "/home/moritz/projects/toga_venv/lib/python3.4/site-packages/toga/interface/window.py", line 127, in toolbar
    self._set_toolbar(items)
  File "/home/moritz/projects/toga_venv/lib/python3.4/site-packages/toga_gtk/window.py", line 42, in _set_toolbar
    item_impl.set_icon_widget(toolbar_item.icon._impl_32)
  File "/home/moritz/projects/toga_venv/lib/python3.4/site-packages/toga_gtk/widgets/icon.py", line 28, in <lambda>
    _impl_32 = property(lambda self: self.__impl(32))
  File "/home/moritz/projects/toga_venv/lib/python3.4/site-packages/toga_gtk/widgets/icon.py", line 23, in __impl
    GdkPixbuf.Pixbuf.new_from_file(self._filename).scale_simple(size, size, GdkPixbuf.InterpType.BILINEAR)
GLib.Error: g-file-error-quark: Datei »/home/moritz/projects/toga_venv/lib/python3.4/site-packages/resources/tiberius.icns« konnte nicht geöffnet werden: Datei oder Verzeichnis nicht gefunden (4)

**Comment by freakboy3742** [comment]
I believe this problem has been addressed by pybee/toga#122 - if you install toga-demo from a github checkout and you still get this problem, please reopen this ticket.
