### ISSUE TITLE
toga-demo 0.2.14 problem with toga.SEPARATOR

### ISSUE THREAD

**Issue by selasley** [pybee/toga-demo#15]
I tried running the toga-demo 0.2.14 with python3.6.2 under OS X 10.12.6 and got this traceback

Traceback (most recent call last):
  File "toga214/bin/toga-demo", line 11, in <module>
    sys.exit(run())
  File "/Users/selasley/toga214/lib/python3.6/site-packages/toga_demo/__main__.py", line 5, in run
    main().main_loop()
  File "/Users/selasley/toga214/lib/python3.6/site-packages/toga_cocoa/app.py", line 167, in main_loop
    self._startup()
  File "/Users/selasley/toga214/lib/python3.6/site-packages/toga_cocoa/app.py", line 118, in _startup
    self.startup()
  File "/Users/selasley/toga214/lib/python3.6/site-packages/toga_demo/app.py", line 55, in startup
    self.main_window.toolbar = [cmd1, toga.SEPARATOR, cmd2]
AttributeError: module 'toga' has no attribute 'SEPARATOR'

The demo runs and buttons and menus work after changing line 55 in toga_demo/app.py from
self.main_window.toolbar = [cmd1, toga.SEPARATOR, cmd2]
to
self.main_window.toolbar.add(cmd1, cmd2)

but it displays this traceback in the Terminal

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/Users/selasley/toga214/lib/python3.6/site-packages/rubicon/objc/objc.py", line 1050, in _objc_method
    result = f(py_self, *args)
  File "/Users/selasley/toga214/lib/python3.6/site-packages/toga_cocoa/app.py", line 55, in application_openFiles_
    for i in range(0, len(filenames)):
TypeError: object of type 'ObjCInstance' has no len()

This traceback is also displayed for the scripts in the toga tutorial.

Thanks for creating toga and the whole BeeWare project.

**Comment by freakboy3742** [comment]
Thanks for the report. Your change to `toolbar.add()` is clearly correct, which is an oversight on my part. The subsequent error appears to be an issue with Rubicon; can you confirm the version of Rubicon that is installed?

**Comment by selasley** [comment]
pip list shows rubicon-objc 0.2.7

**Comment by selasley** [comment]
I added some lines to print the type and dir of filename

<class 'rubicon.objc.objc.ObjCInstance'>

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_as_parameter_', '_cached_objects', 'objc_class', 'ptr']

**Comment by csawyerYumaed** [comment]
using latest git head of toga-demo and changing the line per @selasley 

I get this:
Traceback (most recent call last):
  File "/usr/local/bin//toga-demo", line 11, in <module>
    load_entry_point('toga-demo', 'console_scripts', 'toga-demo')()
  File "~/src/toga-demo/toga_demo/__main__.py", line 5, in run
    main().main_loop()
  File "/usr/local/lib/python3.6/site-packages/toga_cocoa/app.py", line 167, in main_loop
    self._startup()
  File "/usr/local/lib/python3.6/site-packages/toga_cocoa/app.py", line 118, in _startup
    self.startup()
  File "~/src/toga-demo/toga_demo/app.py", line 55, in startup
    self.main_window.toolbar = [cmd1, cmd2]
AttributeError: can't set attribute

versions from pip3 list:
toga (0.2.14)
toga-cocoa (0.2.14)
toga-core (0.2.14)
toga-demo (0.2.13, ~/src/toga-demo)
